version: 0.1.{build}

branches:
  only:
    - master

max_jobs: 1

image:
- Visual Studio 2019

init:
  - git config --global core.autocrlf input

clone_depth: 1

hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2

platform: x64
configuration: Release

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

build_script:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64;C:\Program Files\Git\usr\bin;%PATH%
  - SET PYTHON=C:\Python36-x64\python.exe
  - C:\Python36-x64\python.exe -m pip install pip --upgrade
  - C:\Python36-x64\python.exe -m pip install conan flawfinder
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - curl -o mkn.exe -L https://github.com/Dekken/maiken/raw/binaries/win10_x64/mkn.exe
  - call mkn.bat
  - rm "C:\Program Files\Git\usr\bin\link.exe" # messes with msvc link.exe
  - bash -c "PATH=\"$PWD:/c/Python36-x64/:/c/Program Files/Git/usr/bin:$PATH\"; res/appveyor/run.sh"

artifacts:
  - path: '*.tar'

deploy:
- provider: BinTray
  username: dekken
  api_key:
    secure: FGDIE5oZsFn49kRhIK98X2JAqXwvReVl1nSlKNlo3pYCtosD2r9YfkHHhAJcjcyE
  subject: mkn
  repo: parse.yaml
  package: mkn
  publish: true
  override: true
  explode: true
  artifact: /.*\.tar/
  version: master
